# -*- coding: utf-8 -*-
"""Spotify_ETL_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UXF6JNr-AEDekvgE3S_ctERH4th8Jf9
"""

!pip install spotipy

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

!pip install spotipy
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd

#add your keys here
client_credentials_manager = SpotifyClientCredentials(client_id="b3e53cb53cbf46d89426e5246c8f9c8e", client_secret="3e49831e3ab54002b67dbf221dab6b47")

sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)

playlist_link = "https://open.spotify.com/playlist/37i9dQZEVXbNG2KDcFcKOF?si=1333723a6eff4b7f"
playlist_URI = playlist_link.split("/")[-1].split('?')[0]

playlist_URI

data = sp.playlist_tracks(playlist_URI)

type(data.get('track'))

print(data['items'][0]['track'])

print(data['items'][0]['track']['album']['id'])
print(data['items'][0]['track']['album']['name'])
print(data['items'][0]['track']['album']['release_date'])
print(data['items'][0]['track']['album']['total_tracks'])
print(data['items'][0]['track']['album']['external_urls']['spotify'])

print(data['items'][0]['track'])

album_list = []
for row in data['items']:
    album_id = row['track']['album']['id']
    album_name = row['track']['album']['name']
    album_release_date = row['track']['album']['release_date']
    album_total_tracks = row['track']['album']['total_tracks']
    album_url = row['track']['album']['external_urls']['spotify']
    album_element = {'album_id':album_id,
                     'name':album_name, 
                     'release_date':album_release_date,
                     'total_tracks':album_total_tracks,
                     'url':album_url}
    album_list.append(album_element)
print(album_list)

artist_list = []
for row in data['items']:
  for key,value in row.items():
    if key=='track':
      for artist in value['artists']:
        artist_dict = {'artist_id':artist['id'],
                       'artist_name':artist['name'],
                       'artist_url':artist['href'],
                       }
        artist_list.append(artist_dict)
print(artist_list)

song_list = []
for row in data['items']:
    song_id = row['track']['id']
    song_name = row['track']['name']
    song_duration = row['track']['duration_ms']
    song_url = row['track']['external_urls']['spotify']
    song_popularity = row['track']['popularity']
    song_added_at = row['added_at']
    album_id = row['track']['album']['id']
    artist_id = row['track']['album']['artists'][0]['id']
    song_dict = {'song_id' : song_id,
                 'song_name' : song_name,
                 'song_duration' : song_duration,
                 'song_url' : song_url,
                 'song_popularity' : song_popularity,
                 'song_added_at' : song_added_at,
                 'album_id' : album_id,
                 'artist_id' : artist_id}
    song_list.append(song_dict)
print(song_list)

import pandas as pd
album_df = pd.DataFrame.from_dict(album_list)
artist_df = pd.DataFrame.from_dict(artist_list)
song_df = pd.DataFrame.from_dict(song_list)

print(album_df.info())
print(artist_df.info())
print(song_df.info())

artist_df

song_df

album_df['release_date'] = pd.to_datetime(album_df['release_date'])

album_df.info()

song_df['song_added_at'] = pd.to_datetime(song_df['song_added_at'])

song_df.info()